from base import *

class Parameters(PhitsObject):
    """A "dictionary with an attitude" representing an entry in the [Parameters] section of an input file.
    Any extra keyword arguments to any constructors are minted into parameter objects.


    >>> print(Parameters(ndedx=2, dbcutoff=3.3).definition())
    ndedx = 2
    dbcutoff = 3.3

    """
        syntax = {"control": ("icntl",
                              FinBij({"normal": 0, "output_cross-section": 1, "output_echo_only": 3, "all_reg_void": 5,
                                      "source_check": 6, "show_geometry": 7, "show_geometry_with_xyz": 8, "show_regions": 9,
                                      "show_regions_with_tally": 10, "show_3d_geometry": 11, "use_dumpall": 12, "sum_tally": 13,
                                      "auto_volume": 14, "ww_bias_tally": 15, "analysis_script": 16, "anatally": 17}), None),
                  "max_histories": ("maxcas", PosInt(), None),
                  "max_batches": ("maxbch", PosInt(), None),
                  "nuclear_memory_rescale": ("xsmemory", 1.0, PosReal(), None),
                  "timeout": ("timeout", NegDisable(), None),
                  "stdev_control": ("istdev", FinBij({-2: "history_restart", -1: "batch_restart", 0: "normal", 1: "batch", 2: "history"}), None),
                  "share_tallies": ("italsh", Choice10(), None),
                  "check_consistency": ("ireschk", Choice10(c_style=True), None),
                  "xor_prng": ("nrandgen", Choice10(), None),
                  "seed_skip": ("irskeep", Integer(), None),
                  "random_seed": ("rseed", Real(), None),
                  "seed_from_time": ("itimrand", Choice10(), None),
                  # bitrseed?,

                  "proton_e_cutoff": ("emin(1)", PosReal(), None),
                  "neutron_e_cutoff": ("emin(2)", PosReal(), None),
                  "pionp_e_cutoff": ("emin(3)", PosReal(), None),
                  "pion0_e_cutoff": ("emin(4)", PosReal(), None),
                  "pionm_e_cutoff": ("emin(5)", PosReal(), None),
                  "muonp_e_cutoff": ("emin(6)", PosReal(), None),
                  "muonm_e_cutoff": ("emin(7)", PosReal(), None),
                  "kaonp_e_cutoff": ("emin(8)", PosReal(), None),
                  "kaon0_e_cutoff": ("emin(9)", PosReal(), None),
                  "kaonm_e_cutoff": ("emin(10)", PosReal(), None),
                  "other_e_cutoff": ("emin(11)", PosReal(), None),
                  "electron_e_cutoff": ("emin(12)", PosReal(), None),
                  "positron_e_cutoff": ("emin(13)", PosReal(), None),
                  "photon_e_cutoff": ("emin(14)", PosReal(), None),
                  "deuteron_e_cutoff": ("emin(15)", PosReal(), None),
                  "triton_e_cutoff": ("emin(16)", PosReal(), None),
                  "he3_e_cutoff": ("emin(17)", PosReal(), None),
                  "he4_e_cutoff": ("emin(18)", PosReal(), None),
                  "nucleon_e_cutoff": ("emin(19)", PosReal(), None),
                  "proton_e_max": ("dmax(1)", PosReal(), None),
                  "neutron_e_max": ("dmax(2)", PosReal(), None),
                  "electron_e_max": ("dmax(12)", PosReal(), None),
                  "positron_e_max": ("dmax(13)", PosReal(), None),
                  "photon_e_max": ("dmax(14)", PosReal(), None),
                  "deuteron_e_max": ("dmax(15)", PosReal(), None),
                  "he4_e_max": ("dmax(18)", PosReal(), None),
                  "photonuclear_e_max": ("dpnmax", PosReal(), None),
                  # lib(i)??
                  "proton_react_cutoff": ("cmin(1)", PosReal(), None),
                  "neutron_react_cutoff": ("cmin(2)", PosReal(), None),
                  "pionp_react_cutoff": ("cmin(3)", PosReal(), None),
                  "pion0_react_cutoff": ("cmin(4)", PosReal(), None),
                  "pionm_react_cutoff": ("cmin(5)", PosReal(), None),
                  "muonp_react_cutoff": ("cmin(6)", PosReal(), None),
                  "muonm_react_cutoff": ("cmin(7)", PosReal(), None),
                  "kaonp_react_cutoff": ("cmin(8)", PosReal(), None),
                  "kaon0_react_cutoff": ("cmin(9)", PosReal(), None),
                  "kaonm_react_cutoff": ("cmin(10)", PosReal(), None),
                  "other_react_cutoff": ("cmin(11)", PosReal(), None),
                  "electron_react_cutoff": ("cmin(12)", PosReal(), None),
                  "positron_react_cutoff": ("cmin(13)", PosReal(), None),
                  "photon_react_cutoff": ("cmin(14)", PosReal(), None),
                  "deuteron_react_cutoff": ("cmin(15)", PosReal(), None),
                  "triton_react_cutoff": ("cmin(16)", PosReal(), None),
                  "he3_react_cutoff": ("cmin(17)", PosReal(), None),
                  "he4_react_cutoff": ("cmin(18)", PosReal(), None),
                  "nucleon_react_cutoff": ("cmin(19)", PosReal(), None),
                  "charged_e_min": ("esmin", PosReal(), None),
                  "charged_e_max": ("esmax", PosReal(), None),
                  "electron_positron_track_structure_e_min": ("etsmin", PosReal(), None),
                  "electron_positron_track_structure_e_max": ("etsmax", PosReal(), None),
                  "nucleon_track_structure_e_max": ("tsmax", PosReal(), None),
                  "electric_transport_type": ("negs", FinBij({"PHITS": -1, "ignore": 0, "EGS5": 1}), None),
                  "automatic_e_bounds": ("nucdata", Choice10(), None),
                  "electron_positron_adjust_weight_over_e_max": ("ieleh", Choice10(), None),
                  "nucleon_nucleus_model_switch_e": ("ejamnu", PosReal(), None),
                  "pion_nucleus_model_switch_e": ("ejampi", PosReal(), None),
                  "isobar_max_e": ("eisobar", PosReal(), None),
                  "isobar_model": ("isobar", Choice10(), None),
                  "bertini_jqmd_switch_e": ("eqmdnu", PosReal(), None),
                  "jqmd_e_min": ("eqmdmin", PosReal(), None),
                  "jqmd_jamqmd_switch_e": ("ejamqmd", PosReal(), None),
                  "incl_control":  ("inclg", FinBij({None: 0, "all": 1, "no_He": 2}), None),
                  "icnl_e_min": ("einclmin", PosReal(), None),
                  "icnl_e_max": ("einclmax", PosReal(), None),
                  "inc_elf_control": ("incelf", Choice10(), None),
                  "icnl_elf_e_min": ("eielfmin", PosReal(), None),
                  "icnl_elf_e_max": ("eielfmax", PosReal(), None),
                  "jqmd_2": ("irqmd", Choice10(), None),
                  "scinful_qmd": ("iscinful", Choice10(), None),
                  "kerma_mode": ("kerma", Choice10(), None),
                  "pseudo_reaction_e": ("epseudo", PosReal(), None),
                  "proton_time_cutoff": ("tmax(1)", PosReal(), None),
                  "neutron_time_cutoff": ("tmax(2)", PosReal(), None),
                  "pionp_time_cutoff": ("tmax(3)", PosReal(), None),
                  "pion0_time_cutoff": ("tmax(4)", PosReal(), None),
                  "pionm_time_cutoff": ("tmax(5)", PosReal(), None),
                  "muonp_time_cutoff": ("tmax(6)", PosReal(), None),
                  "muonm_time_cutoff": ("tmax(7)", PosReal(), None),
                  "kaonp_time_cutoff": ("tmax(8)", PosReal(), None),
                  "kaon0_time_cutoff": ("tmax(9)", PosReal(), None),
                  "kaonm_time_cutoff": ("tmax(10)", PosReal(), None),
                  "other_time_cutoff": ("tmax(11)", PosReal(), None),
                  "electron_time_cutoff": ("tmax(12)", PosReal(), None),
                  "positron_time_cutoff": ("tmax(13)", PosReal(), None),
                  "photon_time_cutoff": ("tmax(14)", PosReal(), None),
                  "deuteron_time_cutoff": ("tmax(15)", PosReal(), None),
                  "triton_time_cutoff": ("tmax(16)", PosReal(), None),
                  "he3_time_cutoff": ("tmax(17)", PosReal(), None),
                  "he4_time_cutoff": ("tmax(18)", PosReal(), None),
                  "nucleon_time_cutoff": ("tmax(19)", PosReal(), None),
                  "proton_weight_min": ("wc1(1)", PosReal(), None),
                  "neutron_weight_min": ("wc1(2)", PosReal(), None),
                  "pionp_weight_min": ("wc1(3)", PosReal(), None),
                  "pion0_weight_min": ("wc1(4)", PosReal(), None),
                  "pionm_weight_min": ("wc1(5)", PosReal(), None),
                  "muonp_weight_min": ("wc1(6)", PosReal(), None),
                  "muonm_weight_min": ("wc1(7)", PosReal(), None),
                  "kaonp_weight_min": ("wc1(8)", PosReal(), None),
                  "kaon0_weight_min": ("wc1(9)", PosReal(), None),
                  "kaonm_weight_min": ("wc1(10)", PosReal(), None),
                  "other_weight_min": ("wc1(11)", PosReal(), None),
                  "electron_weight_min": ("wc1(12)", PosReal(), None),
                  "positron_weight_min": ("wc1(13)", PosReal(), None),
                  "photon_weight_min": ("wc1(14)", PosReal(), None),
                  "deuteron_weight_min": ("wc1(15)", PosReal(), None),
                  "triton_weight_min": ("wc1(16)", PosReal(), None),
                  "he3_weight_min": ("wc1(17)", PosReal(), None),
                  "he4_weight_min": ("wc1(18)", PosReal(), None),
                  "nucleon_weight_min": ("wc1(19)", PosReal(), None),
                  "proton_weight_cutoff": ("wc2(1)", PosReal(), None),
                  "neutron_weight_cutoff": ("wc2(2)", PosReal(), None),
                  "pionp_weight_cutoff": ("wc2(3)", PosReal(), None),
                  "pion0_weight_cutoff": ("wc2(4)", PosReal(), None),
                  "pionm_weight_cutoff": ("wc2(5)", PosReal(), None),
                  "muonp_weight_cutoff": ("wc2(6)", PosReal(), None),
                  "muonm_weight_cutoff": ("wc2(7)", PosReal(), None),
                  "kaonp_weight_cutoff": ("wc2(8)", PosReal(), None),
                  "kaon0_weight_cutoff": ("wc2(9)", PosReal(), None),
                  "kaonm_weight_cutoff": ("wc2(10)", PosReal(), None),
                  "other_weight_cutoff": ("wc2(11)", PosReal(), None),
                  "electron_weight_cutoff": ("wc2(12)", PosReal(), None),
                  "positron_weight_cutoff": ("wc2(13)", PosReal(), None),
                  "photon_weight_cutoff": ("wc2(14)", PosReal(), None),
                  "deuteron_weight_cutoff": ("wc2(15)", PosReal(), None),
                  "triton_weight_cutoff": ("wc2(16)", PosReal(), None),
                  "he3_weight_cutoff": ("wc2(17)", PosReal(), None),
                  "he4_weight_cutoff": ("wc2(18)", PosReal(), None),
                  "nucleon_weight_cutoff": ("wc2(19)", PosReal(), None),
                  "proton_source_weight_min": ("swc1(1)", PosReal(), None),
                  "neutron_source_weight_min": ("swc1(2)", PosReal(), None),
                  "pionp_source_weight_min": ("swc1(3)", PosReal(), None),
                  "pion0_source_weight_min": ("swc1(4)", PosReal(), None),
                  "pionm_source_weight_min": ("swc1(5)", PosReal(), None),
                  "muonp_source_weight_min": ("swc1(6)", PosReal(), None),
                  "muonm_source_weight_min": ("swc1(7)", PosReal(), None),
                  "kaonp_source_weight_min": ("swc1(8)", PosReal(), None),
                  "kaon0_source_weight_min": ("swc1(9)", PosReal(), None),
                  "kaonm_source_weight_min": ("swc1(10)", PosReal(), None),
                  "other_source_weight_min": ("swc1(11)", PosReal(), None),
                  "electron_source_weight_min": ("swc1(12)", PosReal(), None),
                  "positron_source_weight_min": ("swc1(13)", PosReal(), None),
                  "photon_source_weight_min": ("swc1(14)", PosReal(), None),
                  "deuteron_source_weight_min": ("swc1(15)", PosReal(), None),
                  "triton_source_weight_min": ("swc1(16)", PosReal(), None),
                  "he3_source_weight_min": ("swc1(17)", PosReal(), None),
                  "he4_source_weight_min": ("swc1(18)", PosReal(), None),
                  "nucleon_source_weight_min": ("swc1(19)", PosReal(), None),
                  "weight_window_max": ("wupn", PosReal(), None),
                  "survival_weight": ("wsurvn", PosReal(), None),
                  "max_split": ("mxwpln", PosReal(), None),
                  "window_at": ("mwhere", FinBij({"reaction": -1, "both": 0, "reg_crossing": 1})),
                  "ww_bias": ("iwwbias", Choice10(), None),
                  "std_cutoff": ("istdcut", Choice10(), None),
                  "only_cut_after_batch": ("istdbat", PosInt(), None),
                  "stopping_model": ("ndedx", FinBij({"SPAR_nucleus_only+NTMC": 0, "ATIMA+NTMC": 1, "SPAR+NTMC": 2, "ATIMA": 3})),
                  "atima_db_max": ("mdbatima", PosInt(), None),
                  "atima_e_cutoff": ("dbcutoff", PosReal(), None),
                  "atima_water_ion_e": ("ih2o", NegDisable(), None),
                  "atima_effective_charge": ("ifixchg", Choice10(), None),
                  "restricted_delta_LET": ("irlet", Choice10(), None),
                  "elastic_scattering": ("ielas", FinBij({None: 0, "neutron": 1, "both": 2}), None),
                  "elastic_angle_groups": ("ielms", PosInt(), None),
                  "nucleon_model": ("icxnp", FinBij({"JAM": 0, "JENDL": 1}), None),
                  "nucleon_nucleus_model": ("icxsni", FinBij({"Perlstein-Niita": 0, "KUROTAMA": 1, "Sato": 2}), None),
                  "nucleus_nucleus_model": ("icrhi", FinBij({"Shen": 0, "NASA": 1, "KUROTAMA": 2}), None),
                  "deuteron_model": ("icrdm", FinBij({"nuclear": 0, "MWO": 1}), None),
                  "pion_induced_model": ("icxspi", FinBij({"geometrical": 0, "Hashimoto": 1}), None),
                  "evap_model": ("nevap", FinBij({None: 0, "GEM": 3}), None),
                  "gem_version": ("ngem", FinBij({1: 1, 2: 2}), None),
                  "fission_model": ("ifission", FinBij("PHITS": 1, "Iwamoto": 2), None),
                  "gamma_decay_model": ("igamma", FinBij({None: 0, "PHITS": 1, "EBITEM": 2, "EBITEM isomer": 3,
                                                          "PHITS no Doppler": -1, "EBITEM no Doppler": -2, "EBITEM no Doppler": -3})),
                  "statistical_multifrag_model": ("ismm", Choice10(), None),
                  "event_generator": ("e-mode", FinBij({None: 0, "simple": 1, "complicated": 2})),
                  "event_generator_max_e": ("em-emode", PosReal(), None),
                  # etc.
                  }

    def __init__(self, **kwargs):
        self.name = "parameters"
        for k, v in kwargs.items():
            assert k in self.syntax, f"Unrecognized parameter {k} (with value {v}) in initialization of Parameters object.
            Check that the correct parameters were passed to other objects."
            setattr(self, k, v)

    def __getitem__(self, key):
        return self.__dict__[key]

    def empty(self):
        return True if self.__dict__ == {"name": "parameters"} else False

    def definition(self):
        inp = ""
        for var, val in  self.__dict__.items():
            if var != "name":
                inp += f"{var} = {val}\n"

        return inp
